"""
Cross-Market Arbitrage Strategy
────────────────────────────────
Core idea: Compare prediction market implied probabilities to equity options
implied volatility/moves. When there's a significant gap between what the
prediction market prices and what the options market implies, trade the
more mispriced side.

Example: If a prediction market contract "Will NVDA drop >10% after earnings?"
prices at 15%, but NVDA options imply a ±12% move (straddle), the prediction
market may be underpricing the downside tail.

For the simulation approach: run the agent swarm to generate a full probability
distribution (not just the mean), and compare the distribution's tail to
options-implied tail probabilities.

Signal logic:
  1. Run swarm simulation → get full distribution of agent estimates
  2. Compute swarm tail probabilities (P(move > X%) from the distribution)
  3. Compare swarm tails to options-implied probabilities (from straddle prices)
  4. Compare swarm mean to prediction market price
  5. Trade the instrument with the larger mispricing
"""

import logging
import numpy as np
from scipy import stats as scipy_stats

from .base import BaseStrategy, StrategySignal

logger = logging.getLogger(__name__)


class CrossMarketArbStrategy(BaseStrategy):
    name = "Cross-Market Arb"
    short_description = "Arb prediction market vs. options implied probabilities"

    def __init__(
        self,
        tail_divergence_threshold: float = 0.08,
        mean_divergence_threshold: float = 0.05,
        base_position_pct: float = 0.03,
        max_position_pct: float = 0.05,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.tail_divergence_threshold = tail_divergence_threshold
        self.mean_divergence_threshold = mean_divergence_threshold
        self.base_position_pct = base_position_pct
        self.max_position_pct = max_position_pct

    def describe(self) -> str:
        return (
            "Cross-Market Arb compares the full probability distribution generated by "
            "the agent swarm to both prediction market prices AND equity options implied "
            "probabilities. It extracts tail probabilities from the swarm distribution "
            "and checks for divergence against options-implied move distributions (derived "
            "from straddle prices and implied volatility). When the swarm sees tail risk "
            "that options are underpricing, or vice versa, the strategy trades the "
            "more mispriced instrument. This exploits the fact that prediction markets "
            "and options markets aggregate different populations of participants with "
            "different information sets."
        )

    def generate_signals(self, events: list[dict]) -> list[StrategySignal]:
        signals = []
        for ev in events:
            eid = ev["event_id"]
            name = ev["event_name"]
            mp = ev["market_probability"]
            ctx = ev.get("context", "")

            # Options-implied data (if provided)
            implied_vol = ev.get("implied_vol", None)
            implied_move_pct = ev.get("implied_move_pct", None)
            options_tail_prob = ev.get("options_tail_prob", None)

            # Run swarm simulation
            result = self._run_sim(name, context=ctx)

            # Extract the full distribution of agent estimates
            all_probs = []
            for sim in result.simulation_results:
                for est in sim.agent_estimates:
                    all_probs.append(est["final_probability"])

            if len(all_probs) < 20:
                signals.append(StrategySignal(
                    event_id=eid, event_name=name, direction="no_trade",
                    position_size_pct=0, confidence="low", alpha=0,
                    strategy_metadata={"skip_reason": "insufficient agent estimates"},
                ))
                continue

            all_probs = np.array(all_probs)

            # Compute swarm distribution statistics
            swarm_mean = float(np.mean(all_probs))
            swarm_std = float(np.std(all_probs))
            swarm_skew = float(scipy_stats.skew(all_probs))
            swarm_kurtosis = float(scipy_stats.kurtosis(all_probs))

            # Tail probabilities from the swarm
            swarm_p_above_70 = float(np.mean(all_probs > 0.7))
            swarm_p_above_80 = float(np.mean(all_probs > 0.8))
            swarm_p_below_30 = float(np.mean(all_probs < 0.3))
            swarm_p_below_20 = float(np.mean(all_probs < 0.2))

            # If we have options data, compute the cross-market divergence
            if implied_vol is not None and implied_move_pct is not None:
                # Options-implied tail probability (simplified from lognormal)
                # P(move > X%) ≈ 2 * N(-X/σ) for a normal distribution
                options_tail = self._options_implied_tail(implied_vol, implied_move_pct)
                if options_tail_prob is not None:
                    options_tail = options_tail_prob  # Use provided value if available

                # Compare tails
                swarm_tail = swarm_p_above_70 + swarm_p_below_30  # Total tail mass
                tail_divergence = swarm_tail - options_tail
            else:
                # Without options data, fall back to mean divergence vs. prediction market
                tail_divergence = 0.0
                options_tail = None

            # Mean divergence: swarm vs. prediction market
            mean_divergence = swarm_mean - mp

            # Determine signal
            # Priority 1: Cross-market tail arb (if options data available)
            # Priority 2: Mean divergence (swarm vs. prediction market)
            if options_tail is not None and abs(tail_divergence) > self.tail_divergence_threshold:
                # Swarm sees more tail risk than options → buy tail
                # Swarm sees less tail risk than options → sell tail
                if tail_divergence > 0:
                    # Swarm sees more extreme outcomes → prediction market is underpricing
                    direction = "long_yes" if swarm_mean > mp else "long_no"
                    arb_type = "tail_arb_swarm_fatter"
                else:
                    direction = "long_no" if swarm_mean > mp else "long_yes"
                    arb_type = "tail_arb_options_fatter"

                alpha = abs(tail_divergence)
                confidence = "high" if alpha > 0.15 else "medium"

            elif abs(mean_divergence) > self.mean_divergence_threshold:
                # Standard mean-based divergence
                if mean_divergence > 0:
                    direction = "long_yes"
                else:
                    direction = "long_no"
                alpha = abs(mean_divergence)
                arb_type = "mean_divergence"
                confidence = "medium" if result.converged else "low"

            else:
                direction = "no_trade"
                alpha = 0
                arb_type = "none"
                confidence = "low"

            # Size
            if direction != "no_trade":
                strength = min(1.0, alpha / 0.15)
                pos_size = min(self.base_position_pct * (1 + strength * 0.5), self.max_position_pct)
            else:
                pos_size = 0

            signals.append(StrategySignal(
                event_id=eid,
                event_name=name,
                direction=direction,
                position_size_pct=pos_size,
                confidence=confidence,
                alpha=alpha,
                strategy_metadata={
                    "arb_type": arb_type,
                    "swarm_mean": round(swarm_mean, 4),
                    "swarm_std": round(swarm_std, 4),
                    "swarm_skew": round(swarm_skew, 4),
                    "swarm_kurtosis": round(swarm_kurtosis, 4),
                    "swarm_p_above_70": round(swarm_p_above_70, 4),
                    "swarm_p_below_30": round(swarm_p_below_30, 4),
                    "market_prob": round(mp, 4),
                    "mean_divergence": round(mean_divergence, 4),
                    "tail_divergence": round(tail_divergence, 4),
                    "options_tail": round(options_tail, 4) if options_tail is not None else None,
                    "implied_vol": implied_vol,
                },
            ))

        n_trades = sum(1 for s in signals if s.direction != "no_trade")
        logger.info(f"[CrossMarketArb] Generated {n_trades}/{len(signals)} trade signals")
        return signals

    @staticmethod
    def _options_implied_tail(implied_vol: float, threshold_move_pct: float) -> float:
        """
        Estimate the options-implied probability of a move exceeding threshold_move_pct.

        Uses a normal approximation: P(|move| > X) ≈ 2 * Phi(-X/sigma)
        where sigma = implied_vol * sqrt(T) and T is normalized to the relevant period.
        """
        if implied_vol <= 0:
            return 0.0
        # Assume ~1 day event, annualized vol → daily vol
        daily_vol = implied_vol / np.sqrt(252)
        z = threshold_move_pct / daily_vol if daily_vol > 0 else 10
        tail_prob = 2 * scipy_stats.norm.sf(z)  # Two-sided tail
        return float(np.clip(tail_prob, 0, 1))
